### ISSUE TITLE
not all pipeline tags available to templates through $LOCAL_IMAGE_*

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator#131]
We have use case where we need to pull few images as base images from other namespaces and use them in the template. Those images are heavy with a lot of tooling and static. So we pre-build them.
```
  "base_images": {
    "base": {
      "cluster": "https://api.ci.openshift.org",
      "namespace": "azure",
      "name": "plugin-base",
      "tag": "latest"
    },
    "origintest": {
      "cluster": "https://api.ci.openshift.org",
      "namespace": "azure",
      "name": "origin-test",
      "tag": "v3.10"
    }
```

Images got tagged to `pipeline` IS as inputs:
```
 Running [input:root], [input:base], [input:origintest], [release-inputs], src, bin, sync, verify, unit, [output:stable:sync], [images], cluster-launch-e2e-azure 
```

If I try to resolve those in the template I get an error. Anything from ^ input:* is not available.
```
- name: IMAGE_ORIGINTEST
  required: true
```

The right way to get images from other namespaces would be 
```
  "tag_specification": {
    "cluster": "https://api.ci.openshift.org",
    "namespace": "openshift",
    "name": "origin-v3.10",
    "tag": "",
    "tag_overrides": {}
  },
```
But we need to get images from 2 namespaces... 

PR where this was tested:
https://github.com/openshift/release/pull/1374

cc: @bbguimaraes @kargakis 
@openshift/sig-azure

**Comment by stevekuznetsov** [comment]
If they're static, why not just use the pull spec from the registry directly in your template?

**Comment by mjudeikis** [comment]
They are static for now, but it does not say it will stay like this. Its fine for us as long as you say "It is, not a bug, it is a feature" :)

**Comment by stevekuznetsov** [comment]
So to be clear, I would expect the images to be available with `LOCAL_IMAGE_<tag>` as documented [here](https://github.com/openshift/ci-operator/blob/master/TEMPLATES.md#local_image_pipeline-tag). Your example uses `IMAGE_<tag>` which is in correct. If `LOCAL_IMAGE_<tag>` is not working, please let us know and we will fix that bug. In the interim, it looks like you can just use the registry URL for your use-case and not bother with this at all, so you should not be blocked.

**Comment by mjudeikis** [comment]
```
error: could not run steps: template cluster-launch-e2e-azure-conformance has required parameter LOCAL_IMAGE_TESTBASE which is not defined
```
I can see tag is being translated to pipeline imageStream, but code cant access it. So yes, its a bug

**Comment by stevekuznetsov** [comment]
Made an issue: https://jira.coreos.com/browse/DPTP-186

**Comment by droslean** [comment]
We never supported exposing the `base_images` to `IMAGE_<key>` variable to the templates. 
A workaround to achieve this should be by combining the `base_images` with `raw_steps.output_image_tag_step`
```yaml
base_images:
origintest:
  cluster: https://api.ci.openshift.org
  namespace: azure
  name: plugin-base
  tag: latest
raw_steps:
- output_image_tag_step:
   from: origintest
   optional: true
   to:
     as: origintest
```

or by manually defining the value in the template's variable:
```yaml
- name: IMAGE_ORIGINTEST
  value: registry.svc.ci.openshift.org/azure/plugin-base:latest
```
@stevekuznetsov Shall we implement this to avoid those workarounds?

**Comment by stevekuznetsov** [comment]
No, for base images the pull spec should just be used.
