### ISSUE TITLE
RFE: stream pod logs from templates in the job log

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#135]
At the moment, the ci-operator log is streamed in the job log view in prow. It would be nice to mux logs from test pods into that log.

**Comment by droslean** [comment]
The logs from a failed test already appear in the ci-operator logs.  Also, the following option `give-pr-author-access-to-namespace` will grant, the pull request's author, access to the namespace that is being created, for further debugging purposes.

**Comment by kargakis** [comment]
Yes, I think this is fine for now.
