### ISSUE TITLE
ci-operator does not support pulling multiple git repos

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#142]
We want to create a job that tests Azure VM image builds. We have a playbook for building images in openshift-ansible.

The test flow is as follows:
1. run image node build playbook (openshift-ansible)
2. test built image is valid by using it to run a cluster (openshift-azure)
3. tag image and release

This job needs to pull openshift-ansible to do the node build in 1. (either via git for PRs and merges, or the published container image for periodic runs) AND openshift-azure for running the test deployment in 2.. We don't care about the commit pulled in 2.. At the moment, there is no support in ci-operator to make use of `extra_refs` which is not exposed via the downward API in prow. We are going to workaround this by putting openshift-azure in an image and use that directly in the template.

cc @openshift/sig-azure @stevekuznetsov @droslean @smarterclayton @bbguimaraes @petr-muller

**Comment by stevekuznetsov** [comment]
> extra_refs which is not exposed via the downward API in prow. 

It totally is exposed in the downward API, that is how `clonerefs`consumes it upstream.

---

If you are testing `openshift-ansible` pull requests, why can't you write a template that uses the `openshift-azure` container images that are tagged into the release to do the install and verification?

**Comment by kargakis** [comment]
> It totally is exposed in the downward API, that is how clonerefsconsumes it upstream.

It works if I use clonerefs but not if I do skip_cloning=true and use the ci-operator for cloning. Will the ci-operator work if I do the cloning in prow (skip_cloning=false)?

> If you are testing openshift-ansible pull requests, why can't you write a template that uses the openshift-azure container images that are tagged into the release to do the install and verification?

Note that today we start with a periodic and eventually we will also test o-a PRs. openshift-azure is not part of the origin release.

**Comment by stevekuznetsov** [comment]
> It works if I use clonerefs but not if I do skip_cloning=true and use the ci-operator for cloning. Will the ci-operator work if I do the cloning in prow (skip_cloning=false)?

No, but has nothing to do with downwardapi.

> Note that today we start with a periodic and eventually we will also test o-a PRs. openshift-azure is not part of the origin release.

We can hash out more next week in the meeting but you're choosing not to follow the established workflows with ci-operator so I am not surprised it's difficult to make it work

**Comment by kargakis** [comment]
External refs are set in JOB_SPEC only in case you do the cloning in prow
so if you ever want to use them in ci-operator you'd have to fix prow
first.

**Comment by droslean** [comment]
Jira opened for this: https://jira.coreos.com/browse/DPTP-290

**Comment by droslean** [comment]
duplicated with #258
