### ISSUE TITLE
cannot get secrets in the temporary namespace

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#144]
```
$ oc get secrets
Error from server (Forbidden): secrets is forbidden: User "kargakis" cannot list secrets in the namespace "ci-op-2zfnzjw2": no RBAC policy matched
```
Trying to debug a template that uses secrets but I don't have access to them.

@stevekuznetsov @droslean 

/kind bug

**Comment by stevekuznetsov** [comment]
Did you use the flag `--give-pr-author-access-to-namespace` ?

**Comment by kargakis** [comment]
Ah, good question. This is about a periodic job so no PR :/

**Comment by stevekuznetsov** [comment]
If you're debugging, self-provision a namespace and point the tool to it with `--namespace` so you have `admin`?

**Comment by kargakis** [comment]
I'd still like to see the ability to grant access to github teams so we can debug postsubmits and periodics but maybe a different issue.

**Comment by stevekuznetsov** [comment]
The whole point of the CI Operator achitecture is you should be able to 100% reproduce what CI is doing by running the tool so I am missing the "why" here
