### ISSUE TITLE
v3.11 images being published to docker hub under the "latest" tag

### ISSUE THREAD

**Issue by bparees** [openshift/ci-operator#158]
I have twice now observed a :latest image pulled from dockerhub that contained v3.11 content.

@stevekuznetsov @smarterclayton 

/cc @deads2k

**Comment by stevekuznetsov** [comment]
What image? Can you correlate this with the Jenkins jobs listed in the OKD image publishing doc? There were a number of TODOs there.

**Comment by bparees** [comment]
in this case i believe it was the hypershift image.  @deads2k was there and maybe remembers better than me.

**Comment by bparees** [comment]
(previously i believe it was origin-docker-builder but my recollection is even fuzzier on that one and of course we're about to rework how that is published since the repo is changing)

**Comment by smarterclayton** [comment]
When was the last time you saw it happen?

**Comment by smarterclayton** [comment]
Fixed
