### ISSUE TITLE
Target substitution breaks jobs that override `RPM_REPO`

### ISSUE THREAD

**Issue by bbguimaraes** [openshift/ci-operator#160]
[`error: could not run steps: could not get Route for RPM server: routes.route.openshift.io "rpm-repo" not found`](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/10165/pull-ci-openshift-openshift-ansible-310-gcp-major-upgrade/26)

[Job.](https://github.com/openshift/release/blob/6701b541bf3ec4c3c5d96a8937e4f0ff3e8426cb/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml#L3-L74)

**Comment by vrutkovs** [comment]
Correct:
```
Running [input:root], [input:base-without-rpms], [release-inputs], src, rpms, [serve:rpms], base, ansible, [output:stable:ansible], [images], e2e-gcp
```
Broken:
```
Running [input:root], [serve:rpms], [input:base-without-rpms], [release-inputs], src, base, ansible, [output:stable:ansible], [images], e2e-gcp
```

**Comment by smarterclayton** [comment]
You shouldn't have RPM_REPO set on the repo if you want your job created.

**Comment by smarterclayton** [comment]
Basically I forced the thing Steve wants - use a variable like RPM_REPO_OPENSHIFT_ORIGIN.
