### ISSUE TITLE
failed test jobs report incorrect error message

### ISSUE THREAD

**Issue by bparees** [openshift/ci-operator#200]
This job had an (expected) test failure, but instead of reporting that, it reported a confusing top level job failure message of "error: could not run steps: could not wait for pod to complete: could not wait for pod completion: the pod ci-op-dibs34hg/e2e-aws-operator failed after 46m30s (failed containers: test):  unknown"

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/59/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/2

```
--- FAIL: TestClusterImageRegistryOperator (1.13s)
	cluster_image_registry_operator_test.go:25: unexpected error: imageregistries.imageregistry.operator.openshift.io "fake-image-registry" not found
FAIL
FAIL	github.com/openshift/cluster-image-registry-operator/test/e2e	1.148s
2018/11/07 01:15:52 Container test in pod e2e-aws-operator failed, exit code 1, reason Error
2018/11/07 01:23:49 Container teardown in pod e2e-aws-operator completed successfully
2018/11/07 01:23:49 Copying artifacts from e2e-aws-operator into /logs/artifacts/e2e-aws-operator
2018/11/07 01:23:50 Copied 6.35Mi of artifacts from e2e-aws-operator to /logs/artifacts/e2e-aws-operator
2018/11/07 01:23:55 Ran for 50m2s
error: could not run steps: could not wait for pod to complete: could not wait for pod completion: the pod ci-op-dibs34hg/e2e-aws-operator failed after 46m30s (failed containers: test):  unknown
```

/cc @smarterclayton

**Comment by droslean** [comment]
It reported that the `test` container has failed. You can check why it failed in the above lines since we print the errors of any container.

**Comment by bparees** [comment]
it reports that it could not wait for the pod to complete, which implies something timed out or went fundamentally wrong.   The top level error a user is confronted with when they go to the job url(https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/59/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/2) is:


"operator Instantiate the template e2e-aws-operator into the operator namespace and wait for any pods to complete 46m38s"

99% of the time, that means to me that something went wrong in the CI infrastructure and I should just rekick the test and hope for better luck next time, it does not mean to me "your test pod failed, look at the logs to see why"

**Comment by droslean** [comment]
@bparees It reports that is could not wait for pod completion because a container inside this pod has already failed, in this case, `test` container failed. Since we know that the pod will end up failed because one of the containers has already failed, we don't need to wait for the others to be completed, so we exit there. There is also a chance that the pod will hang, and in this case, we timeout and exit.

Maybe the sentence `could not wait for pod to complete: could not wait for pod completion:` is confusing.

**Comment by bparees** [comment]
It should report "container x failed, terminating pod" or something else that makes it clear *why* it is not/did not wait for the pod to complete.

**Comment by droslean** [comment]
@bparees There are other errors that can occur there.  I am hoping that an error like:
`error: could not run steps: didn't wait for the pod to complete: the pod nmoraitis-dev/test-template failed after 4m30s (failed containers: test)` should be clear enough for the user.

**Comment by bparees** [comment]
hopefully we'll learn to understand it, anyway, thanks.
