### ISSUE TITLE
periodic and postsubmit pods end up in the same namespace

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#227]
Postsubmit [here](https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure/9) is created in `ci-op-w9mqhq3g`. Periodic [here](https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-azure-no-running-under-test/2) is created in the same namespace. It probably should not. I would expect the periodic job to end up in its own namespace, otherwise there is potential to step on postsubmits results.

/kind bug
@stevekuznetsov @droslean @bbguimaraes @petr-muller

**Comment by petr-muller** [comment]
Isn't this intentional? The namespace name hash is generated out of all inputs (config, repo sha, base images), so one job should be able to reuse the work done by the other.

**Comment by stevekuznetsov** [comment]
Yeah, this is intentional to reuse. Why would you expect them to be separate?

**Comment by kargakis** [comment]
The only reason for running the same job as a postsubmit and periodic is a repo that doesn't have a lot of activity but that's not our case so probably a non-issue.
