### ISSUE TITLE
[RFE] Default project admins

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator#238]
We run multiple CI jobs in our projects and sometimes when switching between timezones or while colleagues being OoO it is very hard to debug their jobs on CI cluster because only PR author has access to the namespaces.
This, even more, complicates things for "test babysitter" role each week.

The suggestion is to add certain people to the projects Admins by default on each namespace, created in certain projects.

In the example, we could read `OWNERS` file from the project repo and add all approvers to the admin in addition to PR author. So wider team could access namespaces in absence of the original PR author. 

@droslean @bbguimaraes @petr-muller @stevekuznetsov @kargakis 
/kind feature

**Comment by jim-minter** [comment]
+1 - this would be super useful

**Comment by stevekuznetsov** [comment]
Hrm you're really not supposed to be poking around in there often and that smells like a failure for us to provide something else for you. Can you describe your use cases? You  have PRs that stay open for a while and many people go into the namespaces _while the tests run_ to debug? Why not add debug information into the test output so you can have the information even when tests are over? Trying to snipe jobs mid-run seems fragile.

**Comment by mjudeikis** [comment]
@stevekuznetsov we have a big variety of tests cases, and more being added. And to add more complexity our flows are very complex. From creating a cluster, rotating credentials, update cluster, operations activities, scaleup, scaledown, etc etc. 
And things like these: https://github.com/openshift/ci-operator/issues/239 , https://github.com/openshift/ci-operator/issues/237 just from this and last week does not help to debug if we don't have access.

The main challenge is that we do "code handovers", where I come to the office and find 2-3 PR's open from colleagues, which I make sure its merged before I start mine (due rebase hell). And I do same with mine for them. This why sometimes I need to debug and check what is happening with my colleagues PR. Or even simple "can you check why my PR tests are failing or I broke something questions."  

it's not like it does not work for us, but our big pace is creating toil, which we are trying to eliminate. 

p.s. To collect artifacts we should first know what failed so we could collect them. We already collect huge amount of artifacts, but not even those help with flakes or breakages https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml#L367-L384

**Comment by kargakis** [comment]
Yeah, this is not only for poking during runtime but also after the test
completes.
Especially CI issues like the OOM thing are very annoying to debug. This is
also
needed because not every PR author is going to have the ability to get into
a
namespace and debug issues (eg. new hires who are also newcomers to
OpenShift).

**Comment by stevekuznetsov** [comment]
Hrm.... but why not run these using `ci-operator` locally? You'll get an identical environment and manage it yourself. I really don't want to support devs debugging jobs in situ during the run or trying to make sure they get in there before the TTL expires afterword. Always when I debugged confusing and complicated test failures for Origin, the first step was to run it locally (or trigger the remote execution locally) and reproduce. I feel like we've provided the best tools for reproducing a job 1000% identically to CI, why is that not the appropriate avenue?

**Comment by mjudeikis** [comment]
We do use it locally. But not for every PR and every job as it is still very raw and hard to use. Most of the times we need to "go in" is to check failure (environmental or code, flake) which is not replicable locally due to nature of the failure. 

If you are "test babysitter for a week", it's a huge toil to investigate each failure without access to runtimes. Just saying :)

**Comment by stevekuznetsov** [comment]
We also have a staging environment where you can run your jobs, and soon we would like to have a copy-paste-able stanza in job failure logs you can run to replicate a job from your own workstation.

**Comment by stevekuznetsov** [comment]
These days it's literally one command. Sorry, but I don't buy it. When was the last time you tried? We've worked very hard to make it easy. Please give it a chance.

**Comment by stevekuznetsov** [comment]
> Running locally you dont get same result as in CI. 

They do ... and if you have a cluster up locally, run the test 100x and you'll see the flake. The environment is identical and it's only chance you don't see a flake.

**Comment by kargakis** [comment]
> They do ... and if you have a cluster up locally, run the test 100x and you'll see the flake. The environment is identical and it's only chance you don't see a flake.

Well, fwiw, we have cases where we experience flakes only in CI, see https://github.com/openshift/release/issues/2608

**Comment by stevekuznetsov** [comment]
That may be an api.ci issue -- and if you use the single-line-reproducer I am talking about it, you'd have seen it, too ...
