### ISSUE TITLE
Allow exposing the test pod using a Route

### ISSUE THREAD

**Issue by tnozicka** [openshift/ci-operator#244]
`openshift-acme` e2e tests need to be exposed to internet so Let's Encrypt can reach back and validate acme challenges. Have tried doing this whit `ngrok` before but they've introduced 20 req/s rate limit, then serveo.net but that strips the `.well-known` paths. Given the test (created) cluster is not exposed to the internet I can forward request from the e2e pod running in the api.ci cluster but I need that pod to be exposed by a Route. Then it's just a matter of `oc port-forward -n default dc/router 5000:80 &`. This could be helpful e.g. for integration tests, not just e2e.

I propose to extend the `ci-operator` config so every "test" has a `expose_domain` option leading to creation of a Route with that name. If the domain is empty the defaults apply, same for Routes. (And svc targeting the pod.). A think we can just settle for port 5000 and avoid additional config there.

/cc @droslean

**Comment by stevekuznetsov** [comment]
Just add it to your template?

**Comment by tnozicka** [comment]
> Just add it to your template?

I am using a stock e2e, not easy to add it there. and you'd have to add it to all the templates (I want to have e2e with 3.11 and 4.0 in the future. I couldn't find an easy way to extend the test by adding additional template to it and to inject an env var into the e2e pod
