### ISSUE TITLE
e2e-aws jobs failing super fast before running tests.

### ISSUE THREAD

**Issue by deads2k** [openshift/ci-operator#265]
I have a few pulls that are symptomatic like this: https://openshift-gce-devel.appspot.com/pr/openshift_cluster-kube-apiserver-operator/258 that have e2e-aws jobs failing extremely quickly.

@droslean @mfojtik

**Comment by bbguimaraes** [comment]
Explained in private chat, but for the record: this was due to a bad template being accidentally pushed to the cluster. It has been fixed and the pods are now running normally.

/close
