### ISSUE TITLE
Have a more Travis/PAPR-style interface

### ISSUE THREAD

**Issue by cgwalters** [openshift/ci-operator#28]
There's a natural tension between Prow which was designed for Kubernetes, where a centralized repo wants its tests owned by a core set of people, versus a testing system like Travis which is designed to do completely arbitrary things for tens (hundreds?) of thousands of git repositories.

Today AIUI, the Prow/CI configurations are stored in configmaps which are themselves stored in a [git repo](https://github.com/openshift/release) (right?).  Let's say that we wanted to adopt a CI-operator/Prow like flow across a vast array of repositories that make up https://github.com/coreos/ and https://github.com/projectatomic/ 

We really need an easy and obvious way for repo owners to own their builds, just like Travis and PAPR.  

One really cool thing about the CI operator flow is giving a PR an entire OpenShift *namespace*.  I love that idea.  If we had a flow where one could do e.g.:

```yaml
# ci/.osci.yml
container: registry.fedoraproject.org/fedora:28
exec: ci/run.sh
```
```bash
#!/usr/bin/bash
set -xeuo pipefail
yum -y install ...
yum -y install origin-clients
mkdir -p ~/.kube
cp /run/secrets/osci-kubeconfig ~/.kube/config

# Just use this container, or sometimes use oc to create further test pods...
```

That'd be very cool.  A key advantage of this over the current flow is that if I want to test a change to my CI configuration, I can *do that as a pull request on my own project* - it's how Travis and PAPR work today.

**Comment by jlebon** [comment]
Yeah, it'd be nice to have the best of both worlds. The global config approach just doesn't feel maintainable to me. For reference, the `config.yaml` for OpenShift right now is 3,715 lines (IIUC it's [this file](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml), right?). For Kubernetes, that number is... 17,064.

One thing I'm currently experimenting with is using Prow to fire off PAPR jobs. It looks like it should work, though there's still going to be a substantial amount of centralized configuration, though at least the part repo developers care most about will be localized (it'd be pretty sweet if e.g. plugins configuration could be stored in each repo as well). One annoyance is that Prow wants to own reporting statuses back to GitHub, which is something that PAPR currently does pretty well.

**Comment by cgwalters** [comment]
I believe today we could probably have each repo have a generic config that executed a "generic container" that just read the `.osci.yml` from the git repo and used its delegated creds to spawn the specified container in the namespace.  One detail that isn't clear to me is - in Prow, what clones the git repo?  Is it mounted as a PV or it just in the overlayfs?  (Is this `clonerefs`?)  Regardless though we'd need to be sure we "moved" (or at least copied) the git repo exactly into the "target container".
There's probably other details here...but if there isn't opposition I think we could prototype this out pretty easily.

**Comment by cgwalters** [comment]
BTW I have to mention again how much I love the idea of a PR having an entire OpenShift namespace.

**Comment by smarterclayton** [comment]
> Yeah, it'd be nice to have the best of both worlds. The global config approach just doesn't feel maintainable to me. For reference, the config.yaml for OpenShift right now is 3,715 lines (IIUC it's this file, right?). For Kubernetes, that number is... 17,064.

And as I've used it more, I think it's the right decision to centralize.  Centralizing it makes it so much easier to script, automate, and unify.  Teams jobs change rarely.  CI infra is a piece of unified software that benefits from centralization.  That said, the jobs should be easy to use individually, and people should definitely be able to have their own jobs under their own control.

That doesn't mean that a single config file will long endure.  We'll probably start generating / post-processing the config to reduce redundancy.  

Re the .osci approach - I'm not sure it's not easier just to have people open PRs on simple code.  However, I *do* appreciate the value of having teams have their own space to create PR jobs.  The problem is when they need shared resources like secrets that are constrained.

As the dev productivity team spins up, I think we should do some quick sessions on how we can approach this.

**Comment by cgwalters** [comment]
>  I'm not sure it's not easier just to have people open PRs on simple common code. 

I'm willing to *try* this but...we're talking about a whole lot of repositories here.  Let's take a simple example of something 1) in the critical path 2) is nothing at all like the other openshift components: https://github.com/projectatomic/container-storage-setup

This is one where we really want virtualized testing, it's not golang, etc.  Doesn't change frequently today though, but it needs a CI revamp.  

Another random example is say https://github.com/coreos/coreos.fedoraproject.org/ which is golang today and actually deployed as a container, but is otherwise nothing at all like other parts of OpenShift itself.

Other examples:
 - https://github.com/coreos/coreos-metadata
 - https://github.com/coreos/ignition

Both of which don't carry their tests in their repo, it lives in https://github.com/coreos/mantle/tree/master/kola

Our https://github.com/projectatomic/atomic-host-tests/ is Ansible, which we'd still need to continue for a while (we never hooked it up with PAPR even).

**Comment by stevekuznetsov** [comment]
I must have missed this  -- sorry.

For context, the `config.yaml` file was not reasonable for large amounts of users, so we and upstream moved to a tree structure, currently under `ci-operator/jobs/$org/$repo`

I think the current approach with CI Operator can be best described like this:

| Configuration File | Logic |
| -- | -- |
| `prow/config.yaml` | _when_ |

**Comment by stevekuznetsov** [comment]
Tracked in https://jira.coreos.com/browse/DPTP-147
/close
