### ISSUE TITLE
root pipeline image is using baseRef, not PR

### ISSUE THREAD

**Issue by chancez** [openshift/ci-operator#333]
- it seems like my `src` image isn't doing what im expecting it to.
https://github.com/openshift/release/blob/master/ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml#L13 is where i define `project_image`.
- according to https://github.com/openshift/ci-operator/blob/master/ONBOARD.md#source-code-image-target this should be my `src` .
- in my PR https://github.com/operator-framework/operator-metering/pull/685/files#diff-158d372343fa3c186f8e0809681d4a69R21 i add a `operator-courier` (a script) to this src image's Dockerfile.
- it fails to find the script in my tests: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/operator-framework_operator-metering/685/pull-ci-operator-framework-operator-metering-master-verify/343
- based on the artifacts/logs https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-metering/685/pull-ci-operator-framework-operator-metering-master-verify/343/artifacts/build-logs/ im not seeing anything related to it even running in the root.log file (here for your convience: https://gist.github.com/chancez/e1e0185971e4a8adebe55d6792dee8c8)

After investigation of the code I saw that `gitSourceStep` is used for building the pipeline root image, and found this piece of code: https://github.com/openshift/ci-operator/blob/master/pkg/steps/git_source.go#L37 which sets the ref to clone to the baseRef. In most cases, the baseRef is the branch a PR is being merged into, such as `master`, which means that changes to our `root` pipeline image do not get picked up in PRs.

**Comment by stevekuznetsov** [comment]
This is documented and WAI

https://github.com/openshift/ci-operator/blob/master/CONFIGURATION.md#build_rootproject_image

/close
