### ISSUE TITLE
We should be using YAML for our configuration

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-operator#46]
Instead of the JSON files that we currently support. The k8s apimachinery YAML parsing library is the most appropriate one for us to use here.

/kind feature

**Comment by petr-muller** [comment]
/assign

![yatt](https://i.imgflip.com/2gy4sv.jpg)

**Comment by petr-muller** [comment]
What needs to change:
- [ ] Convert all existing JSONs in [openshift/release](https://github.com/openshift/release) [WIP](https://github.com/petr-muller/release/tree/yaml-all-the-things)
- [ ] Change all references to JSONs in [openshift/release](https://github.com/openshift/release) [WIP](https://github.com/petr-muller/release/tree/yaml-all-the-things)

**Comment by stevekuznetsov** [comment]
Note that we don't necessarily need that order, right -- we can switch to use YAML, then continue to read JSON until we migrate

**Comment by petr-muller** [comment]
Yeah. But the migration does not seem to be that hard.
