### ISSUE TITLE
Allow external container images as base

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#54]
It seems I can only use imagestreamtags to base my builds on. It would be nice to allow the use of container images served outside of the cluster. Or maybe this is already supported but I have no idea how to make use of it.

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
I thought we did this for efficiency with pullthrough using the internal registry? I can't remember

/cc @smarterclayton

**Comment by smarterclayton** [comment]
You can get images from another cluster via “cluster”.  We did this because a) you need a cluster anyway, b) the metadata and tagging is easy, and c) that’s how we release.

Just import your images to a namespace.
