### ISSUE TITLE
Provide examples for common use cases

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#56]
I guess this is part of a greater documentation effort but we need examples for most common use cases (eg. a job that builds binaries, a job that builds and runs unit tests, etc.). The only source of examples atm is openshift/release but that shouldn't be the case.

cc @petr-muller

**Comment by petr-muller** [comment]
Definitely agree.

**Comment by kargakis** [comment]
@stevekuznetsov Petr is a member (https://github.com/orgs/openshift/people?utf8=%E2%9C%93&query=petr-muller)....

**Comment by stevekuznetsov** [comment]
very interesting

**Comment by stevekuznetsov** [comment]
@petr-muller I think this is the bug where you have your OpenShift organization membership private somehow on your profile -- I cannot assign you to this repo even with the GitHub UI

**Comment by kargakis** [comment]
It shouldn't be the case. The bot should be able to see private members?

**Comment by petr-muller** [comment]
@stevekuznetsov @kargakis I *think* my membership is public (at least that's what I see [here](https://github.com/orgs/openshift/people?utf8=%E2%9C%93&query=petr-muller)) and I can see many people have Private there.

I've already noticed this around other OpenShift repos. In some, I can assign myself to issues. In other, I cannot.

**Comment by stevekuznetsov** [comment]
Need to dig more into why GitHub doesn't allow this ...

**Comment by stevekuznetsov** [comment]
Looks like you technically did not have read access

**Comment by stevekuznetsov** [comment]
The generator docs cover this now
/close
