### ISSUE TITLE
Let the GitHub PR Author have view (or edit?) access into the namespace created by their tests

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-operator#65]
This helps people iterate on stuff if they login to the api.ci cluster

/cc @bbguimaraes @smarterclayton

**Comment by smarterclayton** [comment]
Should be safe, as long as people can't inject bogus GitHub authors.

**Comment by smarterclayton** [comment]
I mean, I can't trick someone else.  Only people in openshift org should be able to log in (I think....)

**Comment by smarterclayton** [comment]
Yeah.  So only question is whether this needs to be an opt-in flag on ci-operator (I kind of think yes, but could be convinced by arguments).

**Comment by stevekuznetsov** [comment]
Opt-in sounds good, made a JIRA ticket for this
/close
