### ISSUE TITLE
ci-operator should write events when it completes and when it creates a namespace

### ISSUE THREAD

**Issue by smarterclayton** [openshift/ci-operator#68]
So that the event stream contains a record.

@stevekuznetsov now that we are doing a better job at recording events.

**Comment by stevekuznetsov** [comment]
@smarterclayton open questions on this:

 - what administrative debugging workflows is the record used for?
 - what information would be useful in the record?

Can you please update https://jira.coreos.com/browse/DPTP-90

**Comment by droslean** [comment]
@smarterclayton 
Should we make this extensible? I will implement it like:
* Create an event controller.
* Start the event controller as goroutine that waits for an event in the event channel.
* The steps will write in that channel.

What kind of events? We have some acceptance criteria in [DPTP-90](https://jira.coreos.com/browse/DPTP-90). Do we need to add more?

This kind of implementation can satisfy what we actually want or make it simpler?

**Comment by smarterclayton** [comment]
We don't need any extensibility.  I think it would be perfectly sufficient to write the following events:

1. write an event (ignore on error) to the namespace we created containing the details of the job we're creating for (audit who created the namespace)
2. write an event when we start running a job in an existing namespace (same details as 1, but for the alternate flow)
3. write an event (best effort) when the ci-op process succeeds or fails
