### ISSUE TITLE
We need reference for config file

### ISSUE THREAD

**Issue by petr-muller** [openshift/ci-operator#70]
People often ask about a reference documentation for config files. #57 had an ambition to add one but it was not straightforward enough and multiple different proposals were raised there.

The actual content is already written in the form of comments of https://github.com/openshift/ci-operator/blob/master/pkg/api/types.go. It could be possible to generate the reference from there using godoc , as advised in #57 by @stevekuznetsov and @smarterclayton  (see [discussion](https://github.com/openshift/ci-operator/pull/57#discussion_r205493785) and the actual [generated content](https://godoc.org/github.com/openshift/ci-operator/pkg/api)). Personally, I would be more in favor of having a real doc rather than sending a Go code documentation to people.

**Comment by stevekuznetsov** [comment]
Godoc is appealing as we can be more certain that comments on the types in code are in sync with actual state than we can be certain that a doc somewhere out in the wild is up-to-date.

**Comment by petr-muller** [comment]
/close

https://github.com/openshift/ci-operator/pull/105
