### ISSUE TITLE
Artifact location should not be surfaced to the end user

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-operator#71]
Why do we do [this](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/console/master.json#L40-L41):

```json
      "commands": "export ARTIFACT_DIR=/tmp/artifacts; ./test-backend.sh",
      "artifact_dir": "/tmp/artifacts"
```

The user does not care. 

/cc @smarterclayton @droslean @petr-muller @bbguimaraes

**Comment by smarterclayton** [comment]
Because not everyone will use ARTIFACT_DIR

**Comment by stevekuznetsov** [comment]
I don't see a good reason why they shouldn't. If you would like to integrate, do something like:

```sh
MY_SPECIAL_ARTIFACT_VAR="${ARTIFACT_DIR:-"${WHATEVER_ELSE}"}"
```

**Comment by smarterclayton** [comment]
I usually bias towards not having magical env vars (artifact_dir), and simply make them explicit / default.  I consider defaulting artifact dir, but it didn't feel that it dried enough up to be explicit.

**Comment by stevekuznetsov** [comment]
The Prow pod-utils provide `$ARTIFACTS`, we can do the same

**Comment by stevekuznetsov** [comment]
Tracked in https://jira.coreos.com/browse/DPTP-149
/close
