### ISSUE TITLE
Secret injection flow 

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator#77]
We would like to run our E2E tests, which requires some secrets to be injected. Env variables, configMaps.

1. We need a way to create those secrets. Currently, they exist in our `azure` namespace. Ci Operator could copy them to temporary namespace when referred. 
2. It would be great if we could provide PodSpec struct for volumes/secrets/configMaps so we define how things are exposed to the test/build container.

@stevekuznetsov if you think there is a way to achieve this now let me know :) I might miss it in the api model

**Comment by bbguimaraes** [comment]
Documentation for e2e tests should be in `openshift/release` soon, you can
check the PR in the meantime:

https://github.com/openshift/release/pull/1113

**Comment by stevekuznetsov** [comment]
@mjudeikis can you describe what you are trying to achieve here? What are the secrets for? What are they doing? What is their locality??

**Comment by mjudeikis** [comment]
@stevekuznetsov something similar like @bbguimaraes mentioned about templates, but idea is template is overkill or this. We could run all cluster creation command from one of the target containers if we could inject our cloud (azure) secret to them

**Comment by stevekuznetsov** [comment]
Again, what is your goal? Are you trying to run a cloud provisioner for Azure before validating the cluster using Origin e2e? Are you testing the provisioner separately? Let's sit down for a BJNS call to hash this out. /cc @kargakis

**Comment by kargakis** [comment]
We can talk today

**Comment by stevekuznetsov** [comment]
We figured out a path.
/close

**Comment by kargakis** [comment]
FWIW, our solution was to use a template (`--template`) for configuring the test pod to mount our secret, copy the secret over from ci to temp namespace (`--secret-dir`), and use `pipeline:bin` in the pullspec of the pod that runs our tests in order to test against the correctly cloned code.

https://github.com/openshift/release/pull/1164
