### ISSUE TITLE
onboarding doc should provide inventory/description of pertinent ISTs in api.ci

### ISSUE THREAD

**Issue by gabemontero** [openshift/ci-operator#81]
A list of the imagestreamtags in the openshift namespace in api.ci that can be referenced in your ci-operator's config.json, along with information about the contents of each IST, or which openshif/origin Dockerfile they are built from, or how they get updated as PRs in openshift/origin merge, would have proven very useful during my jenkins test-e2e work.

**Comment by gabemontero** [comment]
@stevekuznetsov which team tag would you prefer we use for items on openshift/ci-operator and openshift/release ?

**Comment by stevekuznetsov** [comment]
Not sure what you mean about the test tag. I'll try to ingest this card into our JIRA

**Comment by gabemontero** [comment]
Not test tag, but team tag ... sorry ... I meant is there a @openshift/sig-....... mentions tag I should use on openshift/ci-operator or openshift/release items (vs. just always tagging you) .... I though maybe continuous infra or cd team were appropriate, but wasn't sure and thought I'd ask.

10-4 re: injest into JIRA

**Comment by stevekuznetsov** [comment]
We need to do better with our teams in GItHub and SIG labels... it's a TODO

**Comment by gabemontero** [comment]
cool

**Comment by stevekuznetsov** [comment]
Tracked in https://jira.coreos.com/browse/DPTP-148
/close
