### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator#92]
We would like to move some of our periodic jobs from jenkins to `CI-Operator`

We can't do this because of lack of email notification capability. 

@stevekuznetsov is this on the roadmap somewhere? (Seen the upstream issue 8668 already)

**Comment by stevekuznetsov** [comment]
This should be handled by https://github.com/kubernetes/test-infra/issues/8668 and not ci-operator. 

/close
